name: qapod
description: 'Simple survey stored in a pod.'
publish_to: 'none'
version: 0.0.1+0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  solidpod:
    git:
      url: https://github.com/anusii/solidpod
      ref: dev

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  flutter_markdown: ^0.7.6+2
  gap: ^3.0.1
  intl: ^0.19.0
  markdown_tooltip: ^0.0.6
  package_info_plus: ^8.2.1
  path: ^1.9.0
  rdflib: ^0.2.11
  rename_app: ^1.6.2
  shared_preferences: ^2.5.2
  shared_preferences_web: ^2.4.2
  universal_io: ^2.2.2
  window_manager: ^0.4.3

dependency_overrides:
  flutter_secure_storage_linux: ^2.0.1
  flutter_secure_storage_platform_interface: ^2.0.0
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/markdown/questionnaire.md
    - assets/markdown/small_questionnaire.md
    - assets/markdown/participant.md

# Update icons with `dart run flutter_launcher_icons`

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/images/icon.png'
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: 'assets/images/icon.png'
  windows:
    generate: true
    image_path: 'assets/images/icon.png'
    icon_size: 48
  macos:
    generate: true
    image_path: 'assets/images/icon.png'
